version: '3.7'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    volumes:
      - mysql_data:/var/lib/mysql

  prestashop:
    build:
      context: .
      dockerfile: Dockerfile.prestashop
    environment:
      PS_INSTALL_AUTO: '1'
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWD: prestashop
    volumes:
      - prestashop_data:/var/www/html
    depends_on:
      - mysql
    networks:
      - prestashop_network

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - prestashop
    networks:
      - prestashop_network

volumes:
  mysql_data:
  prestashop_data:
  caddy_data:
  caddy_config:

networks:
  prestashop_network: